project_id = "jocnlpkbaqmriedmbocl"

[functions]
  [functions.admin-ai]
    verify_jwt = true
  [functions.ai-assistant]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.bug-triage]
    verify_jwt = true
  [functions.get-mapbox-token]
    verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
