/// <reference types="npm:@types/react@18.3.1" />
import * as React from 'npm:react@18.3.1'
import {
  Body, Button, Container, Head, Heading, Html, Preview, Section, Text, Hr,
} from 'npm:@react-email/components@0.0.22'
import * as s from './_brand.ts'
import type { TemplateEntry } from './registry.ts'

interface ActionItem {
  title: string
  why: string
  how: string
  priority: 'high' | 'medium' | 'low'
}

interface MetricsBlock {
  pendingDecisions?: number
  autoHandled?: number
  bookingsThisWeek?: number
  newSignupsThisWeek?: number
  stuckDeposits?: number
  openTickets?: number
}

interface Props {
  name?: string
  weekStarting?: string
  summary?: string
  actionItems?: ActionItem[]
  metrics?: MetricsBlock
  briefUrl?: string
}

const priorityColor: Record<string, string> = {
  high: '#dc2626',
  medium: '#d97706',
  low: '#059669',
}

const WeeklyCEOBriefEmail = ({
  name, weekStarting, summary, actionItems = [], metrics = {}, briefUrl,
}: Props) => (
  <Html lang="en" dir="ltr">
    <Head />
    <Preview>Your TacLink weekly brief — {actionItems.length} action items</Preview>
    <Body style={s.main}>
      <Container style={s.container}>
        <Section style={s.header}><Text style={s.brand}>TACLINK · WEEKLY BRIEF</Text></Section>
        <Section style={s.inner}>
          <Heading style={s.h1}>
            {name ? `${name}, here's your week.` : "Here's your week."}
          </Heading>
          {weekStarting && (
            <Text style={muted}>Week of {weekStarting}</Text>
          )}
          {summary && <Text style={s.text}>{summary}</Text>}

          <Hr style={hr} />

          <Heading as="h2" style={h2}>This week's snapshot</Heading>
          <Section style={metricsGrid}>
            <MetricRow label="Pending your decision" value={metrics.pendingDecisions ?? 0} />
            <MetricRow label="Auto-handled by AI" value={metrics.autoHandled ?? 0} />
            <MetricRow label="Bookings this week" value={metrics.bookingsThisWeek ?? 0} />
            <MetricRow label="New signups" value={metrics.newSignupsThisWeek ?? 0} />
            <MetricRow label="Stuck deposits" value={metrics.stuckDeposits ?? 0} />
            <MetricRow label="Open support tickets" value={metrics.openTickets ?? 0} />
          </Section>

          <Hr style={hr} />

          <Heading as="h2" style={h2}>Do these {actionItems.length} things this week</Heading>
          {actionItems.map((item, i) => (
            <Section key={i} style={actionCard}>
              <Text style={{ ...actionTitle, color: priorityColor[item.priority] || '#111' }}>
                {i + 1}. {item.title}
                <span style={priorityBadge(item.priority)}>{item.priority.toUpperCase()}</span>
              </Text>
              <Text style={actionText}><strong>Why:</strong> {item.why}</Text>
              <Text style={actionText}><strong>How:</strong> {item.how}</Text>
            </Section>
          ))}

          {briefUrl && (
            <Section style={{ marginTop: '24px', textAlign: 'center' as const }}>
              <Button style={s.button} href={briefUrl}>Open Cockpit</Button>
            </Section>
          )}

          <Text style={muted}>
            Generated by your AI chief-of-staff. Reply to this email to send feedback to yourself.
          </Text>
        </Section>
        <Section style={s.footer}>Tactical training, locked in.</Section>
      </Container>
    </Body>
  </Html>
)

const MetricRow = ({ label, value }: { label: string; value: number }) => (
  <Section style={metricRow}>
    <Text style={metricLabel}>{label}</Text>
    <Text style={metricValue}>{value}</Text>
  </Section>
)

const priorityBadge = (priority: string): React.CSSProperties => ({
  display: 'inline-block',
  marginLeft: '8px',
  padding: '2px 8px',
  borderRadius: '4px',
  fontSize: '10px',
  fontWeight: 700,
  letterSpacing: '0.05em',
  backgroundColor: (priorityColor[priority] || '#111') + '15',
  color: priorityColor[priority] || '#111',
})

const h2: React.CSSProperties = { fontSize: '16px', fontWeight: 700, color: '#111', margin: '24px 0 12px' }
const hr: React.CSSProperties = { border: 'none', borderTop: '1px solid #e5e7eb', margin: '24px 0' }
const muted: React.CSSProperties = { fontSize: '12px', color: '#6b7280', margin: '8px 0' }
const metricsGrid: React.CSSProperties = { margin: '8px 0' }
const metricRow: React.CSSProperties = {
  display: 'flex', justifyContent: 'space-between', padding: '8px 0',
  borderBottom: '1px solid #f3f4f6',
}
const metricLabel: React.CSSProperties = { fontSize: '13px', color: '#374151', margin: 0 }
const metricValue: React.CSSProperties = { fontSize: '14px', fontWeight: 700, color: '#111', margin: 0, textAlign: 'right' as const }
const actionCard: React.CSSProperties = {
  backgroundColor: '#f9fafb', border: '1px solid #e5e7eb', borderRadius: '8px',
  padding: '14px 16px', margin: '10px 0',
}
const actionTitle: React.CSSProperties = { fontSize: '15px', fontWeight: 700, margin: '0 0 8px' }
const actionText: React.CSSProperties = { fontSize: '13px', color: '#374151', lineHeight: '1.5', margin: '4px 0' }

export const template = {
  component: WeeklyCEOBriefEmail,
  subject: (data: Record<string, any>) => `Your TacLink weekly brief — ${(data?.actionItems?.length ?? 3)} actions`,
  displayName: 'Weekly CEO brief',
  previewData: {
    name: 'Owner',
    weekStarting: '2026-04-27',
    summary: 'Bookings up 24% week-over-week. AI auto-handled 18 messages and 4 review moderations. Two stuck deposits and one dormant top-instructor need a personal touch.',
    actionItems: [
      { title: 'Re-engage SGT Reyes', why: 'Top-rated instructor, no course updates in 3 weeks.', how: 'Send a personal message offering a free listing pack.', priority: 'high' },
      { title: 'Resolve 2 stuck deposits', why: 'Blocking $480 in revenue and souring the customer experience.', how: 'Open Cockpit → Refunds queue → process both.', priority: 'high' },
      { title: 'Approve featured courses for next week', why: 'Featured slots drive 30% of weekend bookings.', how: 'Cockpit → Featured Courses → review AI suggestions.', priority: 'medium' },
    ],
    metrics: {
      pendingDecisions: 6, autoHandled: 22, bookingsThisWeek: 41,
      newSignupsThisWeek: 18, stuckDeposits: 2, openTickets: 3,
    },
    briefUrl: 'https://taclinkapp.com/admin/brief',
  },
} satisfies TemplateEntry

export default WeeklyCEOBriefEmail
